// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnepBLMzt58Itb_5DlqYESw_ojoa6cZBI',
    appId: '1:966147097126:web:36a2a4808f7db0de849ce7',
    messagingSenderId: '966147097126',
    projectId: 'mtg-command-dex',
    authDomain: 'mtg-command-dex.firebaseapp.com',
    storageBucket: 'mtg-command-dex.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCydjQmD9c0gLbQLT2Mo4OlBJA4w0whKhA',
    appId: '1:966147097126:android:6028a492c245b9d1849ce7',
    messagingSenderId: '966147097126',
    projectId: 'mtg-command-dex',
    storageBucket: 'mtg-command-dex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMEsEHCNAIPBO-ljfp_gclB1JYX--Gxk',
    appId: '1:966147097126:ios:c5e2cbe6a28fcb3d849ce7',
    messagingSenderId: '966147097126',
    projectId: 'mtg-command-dex',
    storageBucket: 'mtg-command-dex.appspot.com',
    iosBundleId: 'com.example.commandDex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnMEsEHCNAIPBO-ljfp_gclB1JYX--Gxk',
    appId: '1:966147097126:ios:70dc0194ef9cf38d849ce7',
    messagingSenderId: '966147097126',
    projectId: 'mtg-command-dex',
    storageBucket: 'mtg-command-dex.appspot.com',
    iosBundleId: 'com.example.commandDex.RunnerTests',
  );
}
